apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd  # Namespace where Argo CD itself is running
spec:
  project: default

  source:
    repoURL: https://github.com/efellowsbg/sg-test.git
    targetRevision: main
    path: external-secrets  # Path to your Helm chart folder
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets  # Namespace where the chart will be installed

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
